INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (1, 'Brasil', 'BR');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (2, 'Portugal', 'PT');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (3, 'Estados Unidos', 'EUA');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (4, 'França', 'FR');
