INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (1, 'Brasil', 'BR');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (2, 'Portugal', 'PT');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (3, 'Estados Unidos', 'EUA');
INSERT INTO COUNTRY (ID, NAME, ABBREV_NAME) VALUES (4, 'França', 'FR');

INSERT INTO STATE (ID, NAME, ABBREV_NAME, COUNTRY_ID) VALUES (1, 'Paraná', 'PR', 1);
INSERT INTO STATE (ID, NAME, ABBREV_NAME, COUNTRY_ID) VALUES (2, 'São Paulo', 'SP', 1);
INSERT INTO STATE (ID, NAME, ABBREV_NAME, COUNTRY_ID) VALUES (3, 'Santa Catarina', 'SC', 1);
INSERT INTO STATE (ID, NAME, ABBREV_NAME, COUNTRY_ID) VALUES (4, 'Goiás', 'GO', 1);